# Site settings
title: Sjoerd Langkemper
# email: your-email@domain.com
description: "Web application security"
baseurl: ""
url: "https://www.sjoerdlangkemper.nl"
# github_username:  Sjord
future: false
email: sjoerd-2023&#064;&#108;inuxonl&#121;&#046;&#110;l

# Build settings
markdown: kramdown
permalink: pretty
