# Site settings
title: Sjoerd Langkemper
# email: your-email@domain.com
description: "Web application security"
baseurl: ""
url: "http://www.sjoerdlangkemper.nl/"
github_username:  Sjord

# Build settings
markdown: kramdown
permalink: pretty
