on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: jekyll/jekyll
    steps:
      - uses: actions/checkout@v2
      - run: mkdir .jekyll-cache _site
      - run: jekyll build
      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site
  upload:
    runs-on: ubuntu-latest
    container: amazon/aws-cli
    needs: build
    steps:
      - name: Download built site
        uses: actions/download-artifact@v2
        with:
          name: site
      - run: ls -l
