on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: jekyll/jekyll
    steps:
      - uses: actions/checkout@v2
      - run: mkdir .jekyll-cache _site
      - run: jekyll build
      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download built site
        uses: actions/download-artifact@v2
        with:
          name: site
      - run: aws s3 sync . s3://sjoerdlangkemper.nl --size-only --acl public-read --cache-control "max-age=1209600" --exclude "*.html" --exclude "*.xml"
      - run: aws s3 sync . s3://sjoerdlangkemper.nl --size-only --acl public-read --cache-control "max-age=3600" --exclude "*" --include "*.html"
      - run: aws s3 sync . s3://sjoerdlangkemper.nl --size-only --acl public-read --cache-control "max-age=14400" --exclude "*" --include "*.xml"
