on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: jekyll/jekyll
    steps:
      - uses: actions/checkout@v2
      - run: mkdir .jekyll-cache
      - run: ls -l
      - run: jekyll build