on:
  push:
  schedule:
    - cron: 37 11 * * 3
jobs:
  build:
    runs-on: ubuntu-latest
    container: jekyll/jekyll
    steps:
      - uses: actions/checkout@v4
      - run: mkdir .jekyll-cache _site
      - run: jekyll build
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site
  upload:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: site
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - run: aws s3 sync . s3://sjoerdlangkemper.nl --size-only --acl public-read --cache-control "max-age=1209600" --exclude "*.html" --exclude "*.xml"
      - run: aws s3 sync . s3://sjoerdlangkemper.nl --size-only --acl public-read --cache-control "max-age=3600" --exclude "*" --include "*.html"
      - run: aws s3 sync . s3://sjoerdlangkemper.nl --size-only --acl public-read --cache-control "max-age=14400" --exclude "*" --include "*.xml"
