on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: jekyll/jekyll
    steps:
      - uses: actions/checkout@v2
      - run: mkdir .jekyll-cache _site
      - run: jekyll build
      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site
